apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-backend
  labels:
    app: fintech-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fintech-backend
  template:
    metadata:
      labels:
        app: fintech-backend
    spec:
      containers:
        - name: backend
          image: fintechdev2acraeq3fd.azurecr.io/fintech/backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: db_password
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
